name       : gnome-icon-theme
version    : 3.12.0
release    : 7
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnome-icon-theme/3.12/gnome-icon-theme-3.12.0.tar.xz : 359e720b9202d3aba8d477752c4cd11eced368182281d51ffd64c8572b4e503a
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : The GNOME Icon Theme package contains an assortment of non-scalable icons of different sizes and themes
description: |
    The GNOME Icon Theme package contains an assortment of non-scalable icons of different sizes and themes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icon-naming-utils)
patterns   :
    - /usr/lib64/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 gnome-icon-theme.pc $installdir/usr/lib64/pkgconfig/gnome-icon-theme.pc
    rm -rf $installdir/usr/share/locale
    rm -rf $installdir/usr/share/pkgconfig
